In [1]:
from numpy import array
from numpy.linalg import eig

In [2]:
A = array([[4,4], [4,4]])

In [3]:
values, vectors = eig(A)
print(values)
print(vectors)

[8. 0.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [4]:
# Check A.dot(vectors) = vectors.dot(values)
B = A.dot(vectors[:,0])
B

array([5.65685425, 5.65685425])

In [5]:
C = vectors[:,0] * values[0]
C

array([5.65685425, 5.65685425])

In [6]:
vectors[:,0]

array([0.70710678, 0.70710678])

In [7]:
vectors[:,1]

array([-0.70710678,  0.70710678])