# Principal Component Analysis

In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [2]:
# define matrix
A = array([[1, 2],[3, 4],[5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
# column means
M = mean(A, axis = 0)
M

array([3., 4.])

In [4]:
# center columns by subtracting column means
C = A - M
C

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [5]:
# calculate covariance matrix of centered matrix
V = cov(C.T)
V

array([[4., 4.],
       [4., 4.]])

In [6]:
# factorize covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]


In [7]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
