In [1]:
fruit <- c('aaplel','pear','orange','banana')
print(class(fruit))

[1] "character"


# Factor

In [3]:
# Create a vector
apple_colors <- c('green','green','yellow','red','red','red','green','white')
# Create a factor object
factor_apple <- factor(apple_colors)
# Print the factor
print(factor_apple)
print(nlevels(factor_apple))

[1] green  green  yellow red    red    red    green  white 
Levels: green red white yellow
[1] 4


# List

# Matrix

In [4]:
M = matrix(c(1,2,3,4,5,6,7,8), nrow = 2, ncol = 4, byrow=TRUE)
print(M)
M = matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3)
print(M)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


# Array
 - R viết: số dòng, cố cột, số ma trận
 - Python: số ma trận, số dòng , số cột

In [6]:
a <- array(c('red','green','yellow'),dim=c(3,2,3))
print(a)

, , 1

     [,1]     [,2]    
[1,] "red"    "red"   
[2,] "green"  "green" 
[3,] "yellow" "yellow"

, , 2

     [,1]     [,2]    
[1,] "red"    "red"   
[2,] "green"  "green" 
[3,] "yellow" "yellow"

, , 3

     [,1]     [,2]    
[1,] "red"    "red"   
[2,] "green"  "green" 
[3,] "yellow" "yellow"



# Data Frame

In [8]:
# Create the data Frame
BMI <- data.frame(
gender = c('Male','Male','Female'),
height = c(152,171.5,165),
weight = c(81,93,78),
age = c(42,38,26))
print(BMI)

  gender height weight age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


# Variables

In [13]:
# cach 1
colors <- c('red','green','blue')
print(colors)
# cach 2
numbers = c(10,15.5,7)
print(numbers)
# cach 3 
c(TRUE,FALSE,TRUE,TRUE) -> pass
print(pass)

[1] "red"   "green" "blue" 
[1] 10.0 15.5  7.0
[1]  TRUE FALSE  TRUE  TRUE


In [11]:
?reserved

Reserved                 package:base                  R Documentation

_R_e_s_e_r_v_e_d _W_o_r_d_s _i_n _R

_D_e_s_c_r_i_p_t_i_o_n:

     The reserved words in R's parser are

     'if' 'else' 'repeat' 'while' 'function' 'for' 'in' 'next' 'break'

     'TRUE' 'FALSE' 'NULL' 'Inf' 'NaN' 'NA' 'NA_integer_' 'NA_real_'
     'NA_complex_' 'NA_character_'

     '...' and '..1', '..2' etc, which are used to refer to arguments
     passed down from a calling function, see '...'.

_D_e_t_a_i_l_s:

     Reserved words outside quotes are always parsed to be references
     to the objects linked to in the 'Description', and hence they are
     not allowed as syntactic names (see 'make.names').  They *are*
     allowed as non-syntactic names, e.g. inside backtick quotes.

In [14]:
print(ls())

[1] "a"            "apple_colors" "BMI"          "colors"       "factor_apple"
[6] "fruit"        "M"            "numbers"      "pass"        


# Operators

In [15]:
# Arithmetic Operators
v <- c(2,5.5,6)
t <- c(8,3,4)
print(v+1)

[1] 3.0 6.5 7.0


In [16]:
print(v-t)

[1] -6.0  2.5  2.0


In [17]:
print(v/t)

[1] 0.250000 1.833333 1.500000


In [18]:
print(v%%t)

[1] 2.0 2.5 2.0


In [19]:

print(v%/%t)

[1] 0 1 1


In [20]:
print(v^t)

[1]  256.000  166.375 1296.000


In [21]:
print(v>t)

[1] FALSE  TRUE  TRUE


# Nhập

In [26]:
name <- readline(prompt = 'Enter name:')

Enter name: Tran Hai Binh


In [30]:
age = readline(prompt='Enter age:') 
age = as.interger(age)

Enter age: 25


ERROR: Error in as.interger(age): could not find function "as.interger"


In [31]:
age = as.interger(readline(age))

ERROR: Error in as.interger(readline(age)): could not find function "as.interger"


# Xuất

In [33]:
print('Export')

[1] "Export"


In [34]:
colors = c('red','green','blue')
cat('colors are ', colors,'\n')

colors are  red green blue 


# String

In [35]:
a = 'onee'
b = 'two'
c = 'three'

In [36]:
print(paste(a,b,c))

[1] "onee two three"


In [37]:
print(paste(a,b,c, sep = '-'))

[1] "onee-two-three"


In [38]:
print(paste(a,b,c, sep = ''))

[1] "oneetwothree"


In [39]:
s = 'This is a string'
print(toupper(s))
print(tolower(s))
print(nchar(s))

[1] "THIS IS A STRING"
[1] "this is a string"
[1] 16


In [40]:
s1 = 'Today is a NEw year day'
print(chartr(' ','-', s1))

[1] "Today-is-a-NEw-year-day"


In [41]:
print(s1)

[1] "Today is a NEw year day"


In [42]:
character_list = strsplit(s1,' ')
word_list = unlist(character_list)
print(word_list)

[1] "Today" "is"    "a"     "NEw"   "year"  "day"  


In [43]:
print(word_list)
sorted_list = sort(word_list)
print(sorted_list)

[1] "Today" "is"    "a"     "NEw"   "year"  "day"  
[1] "a"     "day"   "is"    "NEw"   "Today" "year" 


In [44]:
print(date())

[1] "Sat Aug 22 10:49:51 2020"


In [45]:
print(Sys.Date())

[1] "2020-08-22"


In [46]:
d1 = '20-10-2018'
print(d1)
print(as.Date('20/10/2018', format('%d/%m/%Y')))

[1] "20-10-2018"
[1] "2018-10-20"


In [47]:
print(format(Sys.Date(), format='%B %d %Y'))

[1] "August 22 2020"


In [48]:
distance = Sys.Date() - as.Date('2018-01-01')
print(distance)
difftime(Sys.Date(), as.Date('2018-01-01'),units='weeks')

Time difference of 964 days


Time difference of 137.7143 weeks