# ALS factorization

In [ ]:
## GD 

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    '''
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: K * |I| (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''    

    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error between Rij and R_hat_ij
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with alpha and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = np.dot(P,Q) # R hat

        e = 0 # error

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:

            break

    return P, Q

In [ ]:
R = [
     [0, 4.5, 2.0, 0],
     [4, 0, 3.5, 0],
     [0, 5, 0, 2], 
     [0, 3.5, 4.0, 1.0]
    ]

R = np.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 2

 
P = np.random.rand(N,K)
Q = np.random.rand(K,M)


nP, nQ = matrix_factorization(R, P, Q, K, steps=10000)

nR = np.dot(nP, nQ)

nR

array([[3.37694852, 4.46777832, 2.01914341, 1.01341691],
       [3.98606806, 5.30579342, 3.49774642, 1.43793283],
       [3.74028553, 5.0366036 , 5.29222492, 1.78528381],
       [2.5514961 , 3.44516845, 3.93503518, 1.28832403]])

In [ ]:
nP

array([[0.05553699, 1.86507899],
       [0.70941729, 1.9579818 ],
       [1.82707332, 1.39800489],
       [1.43406012, 0.88268529]])

In [ ]:
nQ

array([[0.67715939, 0.94525294, 2.11641309, 0.57445536],
       [1.7904556 , 2.36734307, 1.01958373, 0.52625835]])

In [ ]:
R = [
     [2, 5, 1, 3],
     [4, 0, 0, 1],
     [0, 4, 2, 0], 
     [2, 4, 3, 1],
     [1, 3, 2, 0]
    ]

R = np.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 2

 
P = np.random.rand(N,K)
Q = np.random.rand(K,M)


nP, nQ = matrix_factorization(R, P, Q, K, steps=10000)

nR = np.dot(nP, nQ)

nR

array([[1.80703138, 5.04049046, 1.07795373, 2.95634533],
       [3.84650862, 6.29808155, 5.98099924, 0.99754727],
       [1.82612501, 3.99500823, 2.00339912, 1.67457377],
       [2.1367927 , 3.91520441, 2.97602089, 1.05190645],
       [1.4456125 , 2.89524573, 1.80833126, 1.00619392]])

In [ ]:
nP

array([[0.02387918, 2.06757691],
       [2.48437459, 1.10273101],
       [0.6275322 , 1.27158478],
       [1.15136132, 0.92262137],
       [0.64357567, 0.80764801]])

In [ ]:
nQ

array([[ 1.16632665,  1.46047358,  2.18724456, -0.23433991],
       [ 0.86051476,  2.42100573,  0.49609962,  1.43256638]])

## SGD 
- link https://github.com/albertauyeung/matrix-factorization-in-python

In [ ]:
import numpy as np
from mf import MF

In [ ]:
# Perform training and obtain the user and item matrices 
mf = MF(R, K=2, alpha=0.1, beta=0.01, iterations=1000)
training_process = mf.train()

In [ ]:
mf.full_matrix()

In [ ]:
mf.P

In [ ]:
mf.Q.T