In [46]:
import numpy as np
from numpy import array
from scipy.linalg import svd
from sklearn.decomposition import PCA

In [47]:
def random_matrix(m,n,start,end):
    return np.random.randint(start,end,(m,n))

In [48]:
a = random_matrix(3,2,1,9)
a

array([[5, 5],
       [1, 7],
       [8, 8]])

In [52]:
pca = PCA(2)
pca

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [53]:
pca.fit(a)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [50]:
A =[[1,2],[3,4],[5,6]]

In [8]:
U, s,Vt=svd(A)

In [9]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [10]:
s

array([9.52551809, 0.51430058])

In [11]:
Vt

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [18]:
A = [[1,2,3],[4,5,6],[7,8,9]]

In [19]:
U, s, Vt = svd(A)

In [20]:
U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [21]:
sigma = diag(S)

NameError: name 'diag' is not defined

In [55]:
A = random_matrix(3000,3,1,255)
A

array([[142, 105,  50],
       [ 65, 165,  18],
       [112, 141, 208],
       ...,
       [ 52, 125,  45],
       [237, 174, 194],
       [ 38, 205,   5]])

In [56]:
A.shape

(3000, 3)

In [57]:
A[0:10]

array([[142, 105,  50],
       [ 65, 165,  18],
       [112, 141, 208],
       [107, 104, 132],
       [140, 137, 129],
       [ 26,  45,  16],
       [ 79, 149, 197],
       [130,  89,  85],
       [135, 153, 242],
       [ 47, 157,  55]])

In [58]:
# columns' means
M = np.mean(A.T, axis =1 )
M

array([126.833     , 127.90766667, 127.581     ])

In [59]:
# center columns by subtracting column means
C = A - M
C[0:10]

array([[  15.167     ,  -22.90766667,  -77.581     ],
       [ -61.833     ,   37.09233333, -109.581     ],
       [ -14.833     ,   13.09233333,   80.419     ],
       [ -19.833     ,  -23.90766667,    4.419     ],
       [  13.167     ,    9.09233333,    1.419     ],
       [-100.833     ,  -82.90766667, -111.581     ],
       [ -47.833     ,   21.09233333,   69.419     ],
       [   3.167     ,  -38.90766667,  -42.581     ],
       [   8.167     ,   25.09233333,  114.419     ],
       [ -79.833     ,   29.09233333,  -72.581     ]])

In [62]:
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
V

array([[ 5.26956830e+03,  4.63470293e+01, -4.84031074e+01],
       [ 4.63470293e+01,  5.38768170e+03,  9.84640547e-01],
       [-4.84031074e+01,  9.84640547e-01,  5.37722718e+03]])

In [63]:
V[0:10]

array([[ 5.26956830e+03,  4.63470293e+01, -4.84031074e+01],
       [ 4.63470293e+01,  5.38768170e+03,  9.84640547e-01],
       [-4.84031074e+01,  9.84640547e-01,  5.37722718e+03]])

In [65]:
# factorize covariance matrix
values, vectors = np.linalg.eig(V)
values

array([5238.14466017, 5413.37561189, 5382.95691155])

In [66]:
vectors[0:10]

array([[-0.90529992,  0.41721249, -0.07978588],
       [ 0.28267346,  0.73192904,  0.61998031],
       [-0.31706113, -0.53871478,  0.78055021]])

In [67]:
# project data 
P = vectors.T.dot(C.T)
P.T

array([[   4.39184603,   31.35510678,  -75.96828029],
       [ 101.20630415,   60.38436076,  -57.60355561],
       [  -8.36856995,  -39.92875789,   72.07151984],
       ...,
       [  93.10761416,   11.1381376 ,  -60.29069623],
       [-107.76398045,   43.9184685 ,   71.62993288],
       [ 141.07813532,   85.40007744,  -40.79727708]])